import { triangle } from "../2kyu/insaneColoredTriangles_2kyu";

it("insaneColoredTriangle test", () => {
  expect(triangle("B")).toBe("B");
  expect(triangle("GB")).toBe("R");
  expect(triangle("RGBG")).toBe("B");
  expect(triangle("RBRGBRB")).toBe("G");
  expect(triangle("RBRGBRBGGRRRBGBBBGG")).toBe("G");
  expect(triangle("GGBGBGGRRRRRGRG")).toBe("G");
  expect(
    triangle(
      "GBRRBGBRGGGRGRGGRRRGRRRGGGGBGBBBBRBRRGRGGGGGRRGBBGRBBRGGRBBRBGGGBGRBGRBGBBRGGRRBGGBGGRBGGRRRGGRBGGBGBBGRRBGRGGGGBRRRGRRBGBGGBBBBRGBBGGBGBRBGRGGBBBBBGGGGRGBRBBGRBRBRRBRBRBBRGBRBRGRBRBBGRBRBRGBRRBRBRRBBRBGBRRGRRBBRRRBBGGGBRGBRGBGRGBBGBGBBRRBGBGGGBGRRGRRGRBGBRRBBRGGGGRRGGGGGRBRRGGGRRBBGRRRBGGBRRBBBBRBBBGGBBGBGBRRRRGRRRBBRBGRRBRRRGGRRRRGBGBRGGBBRRGGBRGRGBGBGGGGGBBGRGBBBRRBGGGGBRGBGRGGGGRRBGRRGGGGGRGBGGBRRRRBBRBGBRBBGGRGGBGRBBGRRGBRBGBRRGRGGBRRBRBBGGRBGGGBBBRBGBGRBBBGGRGGRRBBRBRGRRRRGGBRRRBGRBRBRGBGRRBGRBRBBBGBRBBGRBRGGGGGGRRGRRRRGRBBGRRGBRRGRGGBRBRGBBRBRRGBGBGGGG"
    )
  ).toBe("R");
});
